=== dimaandrei/WP-Project1-HTML-JS-/persoane.dtd
<!ELEMENT persoane (persoana+)>

<!ELEMENT persoana (nume, prenume, varsta, adresa,liceu,facultate,carnet)>
<!ATTLIST persoana id CDATA #REQUIRED>
<!ELEMENT adresa (strada, numar,localitate,judet,tara)>
<!ELEMENT nume (#PCDATA)>
<!ELEMENT prenume (#PCDATA)>
<!ELEMENT varsta (#PCDATA)>
<!ELEMENT liceu (#PCDATA)>
<!ELEMENT facultate (#PCDATA)>
<!ELEMENT carnet (#PCDATA)>
<!ELEMENT strada (#PCDATA)>
<!ELEMENT numar (#PCDATA)>
<!ELEMENT localitate (#PCDATA)>
<!ELEMENT judet (#PCDATA)>
<!ELEMENT tara (#PCDATA)>

=== dimaandrei/WP-Project1-HTML-JS-/continut/resurse/persoane.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE persoane SYSTEM "persoane.dtd">

<persoane>
    <persoana id="1">
        <nume>Popescu</nume>
        <prenume>Ion</prenume>
        <varsta>23</varsta>
        <adresa>
            <strada>Aviatiei</strada>
            <numar>105</numar>
            <localitate>Iasi</localitate>
            <judet>Iasi</judet>
            <tara>Romania</tara>
        </adresa>
        <liceu>Colegiul National Stefan cel Mare</liceu>
        <facultate>AC</facultate>
        <carnet>B</carnet>
    </persoana>
    <persoana id="2">
        <nume>Maxim</nume>
        <prenume>Vasile</prenume>
        <varsta>30</varsta>
        <adresa>
            <strada>Tatarasi</strada>
            <numar>103</numar>
            <localitate>Iasi</localitate>
            <judet>Iasi</judet>
            <tara>Romania</tara>
            
        </adresa>
        <liceu>Colegiul Racovita</liceu>
        <facultate>ETTI</facultate>
        <carnet>A2</carnet>
    </persoana>
    <persoana id="3">
        <nume>Pop</nume>
        <prenume>Raul</prenume>
        <varsta>5</varsta>
        <adresa>
            <strada>Florilor</strada>
            <numar>66</numar>
            <localitate>Iasi</localitate>
            <judet>Iasi</judet>
            <tara>Romania</tara>
        </adresa>
        <liceu>Colegiul National</liceu>
        <facultate>DIMA</facultate>
        <carnet>D</carnet>
    </persoana>
</persoane>
